# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name: "NY0510의 무한삽질 블로그"
description: "많은 것을 시도하고 끊임없이 노력하는 학생, 김가온 입니다!"

author:
    youtubeChannel: UCbPHBnYHcUYcWfpIEtn60WA
    discord: "690148325604720660"
    github: NY0510
    email: namnyang0510@gmail.com
    facebook:
    youtubeUser:
    twitter:
    stackoverflow:
    quora:
    linkedin:
    pinterest:
    googlePlus:
    instagram:
    reddit:
    medium:
    tumblr:

copyright:
    year: 2021
    name: NY0510

# Google-analytics
google-analytics:
    id: "G-S51V5E7PLR"

# Disqus
disqus:
    id: ""

# URL
url: "https://blog.namnyang.live" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl: "" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Seoul
permalink: /posts/:title/
# permalink: /:year-:month-:day/:title/

# Pagination
paginate: 6
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
    input: GFM

# Navigation
nav:
    - name: "About"
      url: "/about"
    - name: "Archive"
      url: "/archive"
    - name: "Tags"
      url: "/tags"
    - name: "Github"
      url: "https://github.com/NY0510"

# Sass
sass:
    sass_dir: _sass
    style: :compressed

# Scopes
defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "page"
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-admin

exclude: [vendor]

plugins:
    - jekyll-paginate
    - jekyll-sitemap
